/* American football words for the Bananagrams assistant: NFL teams, cities,
   positions, plays & terms, penalties, stadiums, legendary players, coaches,
   college programs, events, famous moments, and pop culture.
   Each entry: { name, cat, conf?, div?, color? } — conf/div/color apply to
   NFL team entries only. Names are unique across the catalog. */
const BUILTIN_FOOTBALL = [];
(function () {
  const seen = new Set();
  const push = (it) => {
    const key = it.name.toLowerCase();
    if (seen.has(key)) return;
    seen.add(key);
    BUILTIN_FOOTBALL.push(it);
  };
  const add = (cat, names) => { for (const n of names) push({ name: n, cat }); };

  /* --- NFL teams: [city, nickname, conference, division, primary color] --- */
  const TEAMS = [
    ["Buffalo", "Bills", "AFC", "East", "#00338D"],
    ["Miami", "Dolphins", "AFC", "East", "#008E97"],
    ["New England", "Patriots", "AFC", "East", "#002244"],
    ["New York", "Jets", "AFC", "East", "#125740"],
    ["Baltimore", "Ravens", "AFC", "North", "#241773"],
    ["Cincinnati", "Bengals", "AFC", "North", "#FB4F14"],
    ["Cleveland", "Browns", "AFC", "North", "#311D00"],
    ["Pittsburgh", "Steelers", "AFC", "North", "#FFB612"],
    ["Houston", "Texans", "AFC", "South", "#03202F"],
    ["Indianapolis", "Colts", "AFC", "South", "#002C5F"],
    ["Jacksonville", "Jaguars", "AFC", "South", "#006778"],
    ["Tennessee", "Titans", "AFC", "South", "#0C2340"],
    ["Denver", "Broncos", "AFC", "West", "#FB4F14"],
    ["Kansas City", "Chiefs", "AFC", "West", "#E31837"],
    ["Las Vegas", "Raiders", "AFC", "West", "#000000"],
    ["Los Angeles", "Chargers", "AFC", "West", "#0080C6"],
    ["Dallas", "Cowboys", "NFC", "East", "#041E42"],
    ["New York", "Giants", "NFC", "East", "#0B2265"],
    ["Philadelphia", "Eagles", "NFC", "East", "#004C54"],
    ["Washington", "Commanders", "NFC", "East", "#5A1414"],
    ["Chicago", "Bears", "NFC", "North", "#0B162A"],
    ["Detroit", "Lions", "NFC", "North", "#0076B6"],
    ["Green Bay", "Packers", "NFC", "North", "#203731"],
    ["Minnesota", "Vikings", "NFC", "North", "#4F2683"],
    ["Atlanta", "Falcons", "NFC", "South", "#A71930"],
    ["Carolina", "Panthers", "NFC", "South", "#0085CA"],
    ["New Orleans", "Saints", "NFC", "South", "#D3BC8D"],
    ["Tampa Bay", "Buccaneers", "NFC", "South", "#D50A0A"],
    ["Arizona", "Cardinals", "NFC", "West", "#97233F"],
    ["Los Angeles", "Rams", "NFC", "West", "#003594"],
    ["San Francisco", "Forty Niners", "NFC", "West", "#AA0000"],
    ["Seattle", "Seahawks", "NFC", "West", "#002244"],
  ];
  for (const [city, nick, conf, div, color] of TEAMS) {
    push({ name: nick, cat: "NFL Team", conf, div, color });
    push({ name: `${city} ${nick}`, cat: "NFL Team", conf, div, color, full: true });
    push({ name: city, cat: "City", conf, div, color });
  }
  /* Team nicknames & aliases (tiles are letters only, so "49ers" is spelled out above) */
  add("NFL Team", ["Niners", "Bucs", "Pats", "Skins", "Fins", "Jags", "Cards",
    "Hawks", "Bolts", "Cheeseheads", "Steel Curtain", "Purple People Eaters",
    "Legion of Boom", "Monsters of the Midway", "Dawg Pound", "Black Hole",
    "Raider Nation", "Bills Mafia", "Who Dat Nation", "Twelfth Man"]);
  add("City", ["Foxborough", "East Rutherford", "Inglewood", "Santa Clara",
    "Glendale", "Landover", "Canton"]);

  /* --- Positions & roles --- */
  add("Position", ["Quarterback", "Running Back", "Halfback", "Fullback",
    "Tailback", "Wide Receiver", "Slot Receiver", "Tight End", "Center",
    "Guard", "Left Guard", "Right Guard", "Tackle", "Left Tackle",
    "Right Tackle", "Offensive Line", "Offensive Lineman", "Defensive Line",
    "Defensive Lineman", "Defensive End", "Defensive Tackle", "Nose Tackle",
    "Edge Rusher", "Pass Rusher", "Linebacker", "Middle Linebacker",
    "Outside Linebacker", "Inside Linebacker", "Cornerback", "Nickelback",
    "Safety", "Free Safety", "Strong Safety", "Defensive Back", "Secondary",
    "Kicker", "Placekicker", "Punter", "Long Snapper", "Holder", "Returner",
    "Kick Returner", "Punt Returner", "Gunner", "Special Teams", "Backup",
    "Starter", "Rookie", "Veteran", "Captain", "Franchise Quarterback",
    "Game Manager", "Gunslinger", "Dual Threat", "Pocket Passer", "Scatback",
    "Bell Cow", "Ball Carrier", "Ball Hawk", "Shutdown Corner", "Lockdown Corner",
    "Head Coach", "Offensive Coordinator", "Defensive Coordinator",
    "Position Coach", "Play Caller", "General Manager", "Owner", "Scout",
    "Trainer", "Water Boy", "Referee", "Umpire", "Line Judge", "Down Judge",
    "Back Judge", "Field Judge", "Side Judge", "Official", "Zebra",
    "Cheerleader", "Mascot", "Announcer", "Color Commentator", "Sideline Reporter"]);

  /* --- Plays, formations & terms --- */
  add("Play & Term", ["Touchdown", "Field Goal", "Extra Point", "Point After",
    "Two Point Conversion", "Safety", "Kickoff", "Punt", "Onside Kick",
    "Squib Kick", "Pooch Punt", "Coffin Corner", "Fair Catch", "Touchback",
    "Muffed Punt", "Fumble", "Forced Fumble", "Fumble Recovery", "Interception",
    "Pick Six", "Scoop and Score", "Sack", "Strip Sack", "Blitz", "Snap",
    "Hike", "Huddle", "No Huddle", "Audible", "Hail Mary", "Screen Pass",
    "Bubble Screen", "Play Action", "Draw Play", "Bootleg", "Naked Bootleg",
    "Sweep", "Jet Sweep", "Reverse", "Flea Flicker", "Trick Play", "Option",
    "Read Option", "Run Pass Option", "Zone Read", "Triple Option",
    "Quarterback Sneak", "Tush Push", "Brotherly Shove", "Spike", "Kneel",
    "Victory Formation", "Shotgun", "Pistol", "Wildcat", "Single Wing",
    "Wishbone", "Spread Offense", "West Coast Offense", "Air Raid",
    "Ground and Pound", "Air Coryell", "Run and Shoot", "Hurry Up Offense",
    "Two Minute Drill", "Two Minute Warning", "Clock Management", "Hard Count",
    "Snap Count", "Cadence", "Omaha", "Blue Forty Two", "Motion", "Formation",
    "Trips", "Bunch", "Empty Backfield", "I Formation", "Goal Line",
    "Goal Line Stand", "End Zone", "Red Zone", "Line of Scrimmage",
    "Neutral Zone", "Pocket", "Scramble", "Rollout", "Pump Fake", "Play Fake",
    "Handoff", "Pitch", "Lateral", "Toss", "Juke", "Stiff Arm", "Spin Move",
    "Hurdle", "Truck", "Dive", "Leap", "Lambeau Leap", "Gatorade Bath",
    "Touchdown Dance", "Spike the Ball", "Griddy", "Route", "Route Tree",
    "Slant", "Post", "Corner Route", "Go Route", "Fly Route", "Fade",
    "Curl", "Comeback", "Out Route", "In Route", "Dig", "Drag",
    "Crossing Route", "Wheel Route", "Seam", "Flat", "Swing Pass", "Checkdown",
    "Dump Off", "Bomb", "Deep Ball", "Moon Ball", "Dime", "Bullet", "Laser",
    "Spiral", "Wobbler", "Duck", "Catch", "Drop", "Reception", "Completion",
    "Incompletion", "Incomplete Pass", "Yards After Catch", "Yards After Contact",
    "Broken Tackle", "Missed Tackle", "Tackle for Loss", "Big Play",
    "Chunk Play", "Explosive Play", "Splash Play", "Counter", "Trap",
    "Power Run", "Inside Zone", "Outside Zone", "Stretch Play", "Dive Play",
    "Iso", "Lead Block", "Pull", "Pulling Guard", "Pancake Block",
    "Cut Block", "Double Team", "Chip Block", "Stunt", "Twist", "Spy",
    "Quarterback Spy", "Contain", "Gap", "Man Coverage", "Zone Coverage",
    "Cover Zero", "Cover One", "Cover Two", "Cover Three", "Cover Four",
    "Tampa Two", "Press Coverage", "Prevent Defense", "Nickel Defense",
    "Dime Defense", "Base Defense", "Goal Line Defense", "Four Three",
    "Three Four", "Pass Rush", "Bull Rush", "Swim Move", "Rip Move",
    "Speed Rush", "Pressure", "Hurry", "Knockdown", "Batted Pass",
    "Pass Breakup", "Coverage Sack", "Three and Out", "Turnover",
    "Turnover on Downs", "Takeaway", "Giveaway", "First Down", "Second Down",
    "Third Down", "Fourth Down", "Down and Distance", "Third and Long",
    "Third and Short", "Fourth and Inches", "Go for It", "Move the Chains",
    "Chain Gang", "Chains", "Measurement", "Spot", "Pylon", "Hash Marks",
    "Gridiron", "Sideline", "Midfield", "Fifty Yard Line", "Yard Line",
    "Yardage", "Field Position", "Coin Toss", "Heads or Tails", "Defer",
    "Overtime", "Sudden Death", "Halftime", "First Half", "Second Half",
    "First Quarter", "Second Quarter", "Third Quarter", "Fourth Quarter",
    "Timeout", "Challenge", "Challenge Flag", "Red Flag", "Instant Replay",
    "Booth Review", "Under Review", "Call Stands", "Call Confirmed",
    "Reversed", "Chip Shot", "Doink", "Uprights", "Goal Post", "Crossbar",
    "Wide Left", "Wide Right", "Shank", "Hang Time", "Net Punt",
    "Blocked Punt", "Blocked Kick", "Fake Punt", "Fake Field Goal",
    "Blowout", "Shutout", "Comeback", "Upset", "Nail Biter", "Rivalry",
    "Home Field", "Road Game", "Away Game", "Home Game", "Neutral Site",
    "Tailgate", "Tailgating", "Pigskin", "Football", "Oblong", "Laces Out",
    "Helmet", "Face Mask", "Visor", "Chin Strap", "Shoulder Pads",
    "Thigh Pads", "Knee Pads", "Cleats", "Mouthguard", "Mouthpiece",
    "Eye Black", "Jersey", "Uniform", "Throwback", "Wristband", "Playbook",
    "Play Sheet", "Headset", "Kicking Tee", "Kicking Net", "Turf",
    "Artificial Turf", "Natural Grass", "Frozen Tundra", "Dome", "Retractable Roof",
    "Scoreboard", "Jumbotron", "Play Clock", "Game Clock", "Whistle",
    "Penalty Flag", "Yellow Flag", "Bean Bag", "Sideline Marker", "Bench",
    "Locker Room", "Film Room", "Film Study", "Practice Squad", "Injured Reserve",
    "Depth Chart", "Roster", "Fifty Three Man Roster", "Active Roster",
    "Salary Cap", "Cap Space", "Franchise Tag", "Free Agency", "Free Agent",
    "Trade Deadline", "Contract", "Signing Bonus", "Rookie Contract",
    "Holdout", "Waivers", "Cut", "Release", "Retirement", "Comeback Player",
    "Draft", "Draft Pick", "First Round Pick", "First Overall Pick",
    "Mister Irrelevant", "Undrafted", "Draft Bust", "Draft Steal", "Sleeper",
    "Combine", "Forty Yard Dash", "Vertical Jump", "Broad Jump", "Bench Press",
    "Pro Day", "Wonderlic", "Scouting Report", "Mock Draft", "Big Board",
    "Training Camp", "Minicamp", "Preseason", "Regular Season", "Postseason",
    "Playoffs", "Playoff Picture", "Wild Card", "Bye Week", "Bye",
    "Home Field Advantage", "Seed", "Top Seed", "Clinched", "Eliminated",
    "Tiebreaker", "Strength of Schedule", "Winning Streak", "Losing Streak",
    "Undefeated", "Winless", "Perfect Season", "Dynasty", "Rebuild",
    "Tank", "Hot Seat", "Fired", "Hired", "Interim", "Coaching Carousel",
    "Coach of the Year", "Rookie of the Year", "Most Valuable Player",
    "Comeback Player of the Year", "Man of the Year", "Pro Bowl", "Pro Bowler",
    "All Pro", "First Team All Pro", "Hall of Fame", "Hall of Famer",
    "Gold Jacket", "Ring of Honor", "Retired Number", "Legend", "Goat",
    "Greatest of All Time", "Stats", "Stat Line", "Box Score", "Passer Rating",
    "Completion Percentage", "Passing Yards", "Rushing Yards", "Receiving Yards",
    "Yards Per Carry", "Yards Per Attempt", "Total Yards", "Time of Possession",
    "Turnover Margin", "Third Down Conversion", "Red Zone Efficiency",
    "Points Per Game", "Point Spread", "Spread", "Over Under", "Underdog",
    "Favorite", "Upset Alert", "Parlay", "Fantasy Football", "Fantasy Draft",
    "Waiver Wire", "Sleeper Pick", "Flex", "Bench Points", "Trade Rumor",
    "Tampering", "Bulletin Board Material", "Trash Talk", "Chippy",
    "Smash Mouth", "Physical", "Grind It Out", "Bend Dont Break",
    "Prevent Defense Prevents Winning", "Any Given Sunday", "Next Man Up",
    "Take It One Game at a Time", "Control the Clock", "Establish the Run",
    "Win the Line of Scrimmage", "Win the Turnover Battle", "Momentum",
    "Adversity", "Grit", "Toughness", "Heart", "Hustle", "Effort", "Motor",
    "Football IQ", "Vision", "Burst", "Wiggle", "Twitch", "Juice", "Bend",
    "Length", "Frame", "Hands", "Catch Radius", "Arm Talent", "Cannon",
    "Rocket Arm", "Noodle Arm", "Pocket Presence", "Happy Feet",
    "Escapability", "Elusiveness", "Contact Balance", "Sure Tackler",
    "Thumper", "Enforcer", "Hitter", "Big Hit", "Blindside", "Crackback",
    "De-cleater", "Jacked Up", "Lit Up", "Rocked", "Trucked", "Pancaked",
    "Mossed", "Juked Out of His Shoes", "Ankle Breaker", "Broke Ankles",
    "Toe Tap", "Toe Drag", "Sideline Catch", "One Handed Catch", "Helmet Catch",
    "Immaculate Reception", "The Catch", "The Drive", "The Fumble",
    "Music City Miracle", "Minneapolis Miracle", "Philly Special",
    "Butt Fumble", "Fail Mary", "Tuck Rule", "Deflategate", "Spygate",
    "Ice Bowl", "Snow Bowl", "Fog Bowl", "Mud Bowl", "Tuck", "Ice the Kicker"]);

  /* --- Penalties --- */
  add("Penalty", ["Holding", "Offensive Holding", "Defensive Holding",
    "Offside", "Offsides", "False Start", "Encroachment",
    "Neutral Zone Infraction", "Pass Interference",
    "Offensive Pass Interference", "Defensive Pass Interference",
    "Roughing the Passer", "Roughing the Kicker", "Running Into the Kicker",
    "Unnecessary Roughness", "Unsportsmanlike Conduct", "Personal Foul",
    "Facemask", "Horse Collar", "Horse Collar Tackle", "Illegal Formation",
    "Illegal Motion", "Illegal Shift", "Delay of Game", "Intentional Grounding",
    "Illegal Contact", "Illegal Use of Hands", "Hands to the Face", "Clipping",
    "Chop Block", "Tripping", "Targeting", "Taunting", "Too Many Men",
    "Too Many Men on the Field", "Twelve Men on the Field",
    "Illegal Substitution", "Illegal Touching", "Ineligible Receiver",
    "Ineligible Receiver Downfield", "Illegal Forward Pass",
    "Illegal Block in the Back", "Block in the Back", "Illegal Blindside Block",
    "Illegal Crackback", "Leaping", "Leverage", "Excessive Celebration",
    "Fair Catch Interference", "Kick Catch Interference", "Illegal Touch",
    "Illegal Batting", "Illegal Kick", "Illegal Snap", "Palpably Unfair Act",
    "Disqualification", "Ejection", "Flag", "Flag on the Play", "Laundry",
    "Declined", "Accepted", "Offsetting Penalties", "Spot Foul",
    "Loss of Down", "Automatic First Down", "Half the Distance",
    "Five Yard Penalty", "Ten Yard Penalty", "Fifteen Yard Penalty",
    "Repeat the Down", "Replay the Down", "Dead Ball Foul", "Live Ball Foul",
    "Pre Snap Penalty", "Post Play Penalty", "Ticky Tack", "Phantom Call",
    "Make Up Call", "Let Them Play", "Good No Call"]);

  /* --- Stadiums --- */
  add("Stadium", ["Lambeau Field", "Arrowhead Stadium", "Arrowhead",
    "Soldier Field", "MetLife Stadium", "SoFi Stadium", "Lumen Field",
    "Levis Stadium", "Gillette Stadium", "Ford Field", "Lucas Oil Stadium",
    "Mercedes Benz Stadium", "Caesars Superdome", "Superdome",
    "Raymond James Stadium", "Hard Rock Stadium", "Highmark Stadium",
    "Acrisure Stadium", "Heinz Field", "Paycor Stadium", "Huntington Bank Field",
    "M and T Bank Stadium", "NRG Stadium", "Nissan Stadium", "EverBank Stadium",
    "Empower Field", "Mile High", "Mile High Stadium", "Allegiant Stadium",
    "Lincoln Financial Field", "The Linc", "Northwest Stadium", "FedEx Field",
    "US Bank Stadium", "Bank of America Stadium", "State Farm Stadium",
    "AT and T Stadium", "Jerry World", "Texas Stadium", "Candlestick Park",
    "Kingdome", "Astrodome", "Pontiac Silverdome", "Silverdome",
    "Three Rivers Stadium", "Veterans Stadium", "Giants Stadium",
    "RFK Stadium", "Metrodome", "Rose Bowl", "Los Angeles Memorial Coliseum",
    "The Coliseum", "Big House", "Michigan Stadium", "Ohio Stadium",
    "The Horseshoe", "Beaver Stadium", "Death Valley", "Tiger Stadium",
    "Bryant Denny Stadium", "Neyland Stadium", "Kyle Field", "The Swamp",
    "Ben Hill Griffin Stadium", "Sanford Stadium", "Notre Dame Stadium",
    "Memorial Stadium", "Camp Randall", "Kinnick Stadium", "Autzen Stadium",
    "Husky Stadium", "Cotton Bowl", "Frozen Tundra", "The Dawg Pound",
    "The Black Hole", "The Jungle", "The Dome", "The Shoe", "The Coliseum"]);

  /* --- Legendary players --- */
  add("Player", ["Tom Brady", "Jerry Rice", "Joe Montana", "Peyton Manning",
    "Eli Manning", "Archie Manning", "Walter Payton", "Jim Brown",
    "Lawrence Taylor", "Barry Sanders", "Deion Sanders", "Emmitt Smith",
    "Dan Marino", "John Elway", "Brett Favre", "Aaron Rodgers",
    "Patrick Mahomes", "Reggie White", "Ray Lewis", "Rob Gronkowski", "Gronk",
    "Randy Moss", "Terrell Owens", "Johnny Unitas", "Bart Starr", "Dick Butkus",
    "Joe Namath", "Broadway Joe", "Troy Aikman", "Steve Young", "Drew Brees",
    "Marshall Faulk", "LaDainian Tomlinson", "Adrian Peterson", "Calvin Johnson",
    "Megatron", "Aaron Donald", "Travis Kelce", "Jason Kelce", "Josh Allen",
    "Lamar Jackson", "Joe Burrow", "Justin Jefferson", "Tyreek Hill", "Cheetah",
    "Derrick Henry", "King Henry", "Saquon Barkley", "Micah Parsons",
    "Myles Garrett", "Bo Jackson", "Eric Dickerson", "Gale Sayers",
    "Franco Harris", "Terry Bradshaw", "Lynn Swann", "John Stallworth",
    "Roger Staubach", "Dan Fouts", "Warren Moon", "Kurt Warner", "Ed Reed",
    "Troy Polamalu", "Bruce Smith", "Ronnie Lott", "Mike Singletary",
    "Jack Lambert", "Joe Greene", "Mean Joe Greene", "Otto Graham",
    "Sammy Baugh", "Jim Thorpe", "Red Grange", "Bronko Nagurski", "Y A Tittle",
    "Fran Tarkenton", "Roger Craig", "Ronnie Lott", "Charles Woodson",
    "Champ Bailey", "Darrelle Revis", "Richard Sherman", "Earl Thomas",
    "Kam Chancellor", "Marshawn Lynch", "Beast Mode", "Russell Wilson",
    "Cam Newton", "Michael Vick", "Donovan McNabb", "Brian Dawkins",
    "Reggie Bush", "Vince Young", "Matt Ryan", "Julio Jones", "Larry Fitzgerald",
    "Anquan Boldin", "Steve Smith", "Andre Johnson", "JJ Watt", "TJ Watt",
    "Von Miller", "Demarcus Ware", "Julius Peppers", "Jared Allen",
    "Michael Strahan", "Jason Taylor", "Zach Thomas", "Dan Fouts",
    "Junior Seau", "Tony Gonzalez", "Antonio Gates", "Shannon Sharpe",
    "Mike Ditka", "Kellen Winslow", "Ozzie Newsome", "Jim Kelly",
    "Thurman Thomas", "Andre Reed", "Bruce Smith", "OJ Simpson", "Marcus Allen",
    "Howie Long", "Tim Brown", "Ken Stabler", "Bo Jackson", "Ray Guy",
    "Steve Largent", "Cortez Kennedy", "Walter Jones", "Tony Dorsett",
    "Randy White", "Bob Lilly", "Michael Irvin", "Larry Allen", "Jason Witten",
    "DeMarcus Ware", "Tony Romo", "Dak Prescott", "Ezekiel Elliott", "CeeDee Lamb",
    "Dez Bryant", "Phil Simms", "Michael Strahan", "Tiki Barber",
    "Odell Beckham", "Odell Beckham Junior", "Reggie White", "Chris Carter",
    "Cris Carter", "Randall Cunningham", "Adrian Peterson", "Alan Page",
    "Jim Marshall", "Carl Eller", "Anthony Munoz", "Boomer Esiason",
    "Chad Johnson", "Ochocinco", "Ja'Marr Chase", "Bernie Kosar",
    "Jim Kelly", "Josh Cribbs", "Nick Chubb", "Ben Roethlisberger",
    "Big Ben", "Hines Ward", "Jerome Bettis", "The Bus", "Antonio Brown",
    "Le'Veon Bell", "Rod Woodson", "Lynn Swann", "Mel Blount", "Andrew Luck",
    "Marvin Harrison", "Reggie Wayne", "Edgerrin James", "Dwight Freeney",
    "Robert Mathis", "Steve McNair", "Eddie George", "Fred Taylor",
    "Maurice Jones Drew", "Trevor Lawrence", "Jimmy Johnson", "Deshaun Watson",
    "DeAndre Hopkins", "CJ Stroud", "Terrell Davis", "Shannon Sharpe",
    "Rod Smith", "Champ Bailey", "Priest Holmes", "Tony Gonzalez",
    "Derrick Thomas", "Jamaal Charles", "Len Dawson", "Philip Rivers",
    "Junior Seau", "Justin Herbert", "Dan Fouts", "Charles Woodson",
    "Tim Brown", "Derek Carr", "Davante Adams", "Maxx Crosby", "Joe Flacco",
    "Jonathan Ogden", "Ed Reed", "Ray Lewis", "Terrell Suggs", "Haloti Ngata",
    "Ryan Tannehill", "Jason Taylor", "Larry Csonka", "Bob Griese",
    "Dan Marino", "Jim Kelly", "Stefon Diggs", "Curtis Martin", "Mark Sanchez",
    "Darrelle Revis", "Wayne Chrebet", "Ty Law", "Tedy Bruschi", "Vince Wilfork",
    "Julian Edelman", "Wes Welker", "Adam Vinatieri", "Justin Tucker",
    "Morten Andersen", "Gary Anderson", "Jan Stenerud", "Sebastian Janikowski",
    "Shane Lechler", "Devin Hester", "Dante Hall", "Brian Urlacher",
    "Walter Payton", "Sweetness", "Mike Singletary", "Jim McMahon",
    "William Perry", "The Refrigerator", "Matt Forte", "Devin Hester",
    "Barry Sanders", "Calvin Johnson", "Matthew Stafford", "Amon Ra St Brown",
    "Jared Goff", "Aidan Hutchinson", "Ray Nitschke", "Reggie White",
    "Donald Driver", "Jordy Nelson", "Davante Adams", "Charles Woodson",
    "Clay Matthews", "Jordan Love", "Randy Moss", "Cris Carter", "Fran Tarkenton",
    "Alan Page", "Kirk Cousins", "Dalvin Cook", "Deion Sanders", "Prime Time",
    "Michael Vick", "Matt Ryan", "Julio Jones", "Tony Gonzalez", "Bijan Robinson",
    "Kyle Pitts", "Cam Newton", "Luke Kuechly", "Steve Smith", "Christian McCaffrey",
    "Julius Peppers", "Drew Brees", "Archie Manning", "Alvin Kamara",
    "Michael Thomas", "Reggie Bush", "Rickey Jackson", "Willie Roaf",
    "Derrick Brooks", "Warren Sapp", "Ronde Barber", "John Lynch",
    "Mike Alstott", "Baker Mayfield", "Mike Evans", "Larry Fitzgerald",
    "Kurt Warner", "Kyler Murray", "Pat Tillman", "Aeneas Williams",
    "Marshall Faulk", "Isaac Bruce", "Torry Holt", "Eric Dickerson",
    "Jackie Slater", "Deacon Jones", "Merlin Olsen", "Aaron Donald",
    "Cooper Kupp", "Puka Nacua", "Todd Gurley", "Jerry Rice", "Joe Montana",
    "Steve Young", "Ronnie Lott", "Roger Craig", "Frank Gore", "Patrick Willis",
    "Terrell Owens", "Brock Purdy", "Nick Bosa", "George Kittle", "Deebo Samuel",
    "Steve Largent", "Cortez Kennedy", "Walter Jones", "Shaun Alexander",
    "Marshawn Lynch", "Russell Wilson", "Richard Sherman", "Bobby Wagner",
    "DK Metcalf", "Tyler Lockett", "Kenny Easley", "Jim Zorn", "Kelvin Benjamin",
    "Jalen Hurts", "AJ Brown", "DeVonta Smith", "Brian Dawkins", "Reggie White",
    "Donovan McNabb", "Brian Westbrook", "LeSean McCoy", "Nick Foles",
    "Jason Peters", "Lane Johnson", "Fletcher Cox", "Sonny Jurgensen",
    "Sammy Baugh", "John Riggins", "Art Monk", "Darrell Green", "Joe Theismann",
    "Sean Taylor", "Jayden Daniels", "Terry McLaurin", "Doug Williams",
    "Mark Rypien", "Jim Plunkett", "Tony Dungy", "Bo Jackson", "Herschel Walker",
    "Tim Tebow", "Johnny Manziel", "Colin Kaepernick", "Peyton Hillis"]);

  /* --- Coaches --- */
  add("Coach", ["Vince Lombardi", "Bill Belichick", "Andy Reid", "Don Shula",
    "Tom Landry", "Bill Walsh", "Chuck Noll", "John Madden", "Mike Tomlin",
    "Sean McVay", "Kyle Shanahan", "Mike Shanahan", "George Halas", "Papa Bear",
    "Paul Brown", "Bill Parcells", "Big Tuna", "Jimmy Johnson", "Joe Gibbs",
    "Tony Dungy", "Bill Cowher", "Marv Levy", "Dick Vermeil", "Mike Ditka",
    "Iron Mike", "Bud Grant", "Chuck Knox", "Marty Schottenheimer", "Jon Gruden",
    "Chucky", "Pete Carroll", "John Harbaugh", "Jim Harbaugh", "Sean Payton",
    "Mike McCarthy", "Bruce Arians", "Doug Pederson", "Nick Sirianni",
    "Dan Campbell", "Kevin O'Connell", "Matt LaFleur", "Sean McDermott",
    "Mike Vrabel", "Jim Caldwell", "Tom Coughlin", "Rex Ryan", "Buddy Ryan",
    "Wade Phillips", "Dom Capers", "Dick LeBeau", "Tom Flores", "Hank Stram",
    "Weeb Ewbank", "Sid Gillman", "Curly Lambeau", "Steve Owen", "Bill Belichick",
    "Bill Cowher", "Nick Saban", "Kirby Smart", "Urban Meyer", "Bear Bryant",
    "Paul Bear Bryant", "Bo Schembechler", "Woody Hayes", "Joe Paterno",
    "Knute Rockne", "Lou Holtz", "Steve Spurrier", "Bobby Bowden",
    "Dabo Swinney", "Jim Tressel", "Ryan Day", "Lincoln Riley", "Deion Sanders",
    "Coach Prime", "Eddie Robinson", "Tom Osborne", "Barry Switzer",
    "Pete Carroll", "Mack Brown", "Jimbo Fisher", "Lane Kiffin",
    "Bill Snyder", "Frank Beamer", "Bill O'Brien", "Jim Mora", "Jerry Glanville",
    "Herm Edwards", "Dennis Green", "Mike Holmgren", "Bill Callahan", "Ted Lasso"]);

  /* --- College programs --- */
  add("College", ["Alabama Crimson Tide", "Crimson Tide", "Roll Tide",
    "Ohio State Buckeyes", "Buckeyes", "Michigan Wolverines", "Wolverines",
    "Georgia Bulldogs", "Bulldogs", "Notre Dame Fighting Irish", "Fighting Irish",
    "Notre Dame", "Texas Longhorns", "Longhorns", "Hook Em", "Oklahoma Sooners",
    "Sooners", "Boomer Sooner", "USC Trojans", "Trojans", "LSU Tigers",
    "Geaux Tigers", "Clemson Tigers", "Tigers", "Penn State Nittany Lions",
    "Nittany Lions", "Oregon Ducks", "Ducks", "Florida Gators", "Gators",
    "Florida State Seminoles", "Seminoles", "Tennessee Volunteers", "Volunteers",
    "Vols", "Nebraska Cornhuskers", "Cornhuskers", "Huskers", "Auburn Tigers",
    "War Eagle", "Wisconsin Badgers", "Badgers", "Iowa Hawkeyes", "Hawkeyes",
    "Texas A and M Aggies", "Aggies", "Gig Em", "Miami Hurricanes", "Hurricanes",
    "The U", "Washington Huskies", "Huskies", "Utah Utes", "Utes",
    "Army Black Knights", "Black Knights", "Navy Midshipmen", "Midshipmen",
    "Army Navy Game", "Air Force Falcons", "Colorado Buffaloes", "Buffaloes",
    "Buffs", "Ole Miss Rebels", "Ole Miss", "Rebels", "Hotty Toddy",
    "Mississippi State Bulldogs", "Michigan State Spartans", "Spartans",
    "Oklahoma State Cowboys", "Arkansas Razorbacks", "Razorbacks", "Hogs",
    "Kentucky Wildcats", "Wildcats", "Stanford Cardinal", "UCLA Bruins", "Bruins",
    "Cal Golden Bears", "Golden Bears", "TCU Horned Frogs", "Horned Frogs",
    "Baylor Bears", "Boise State Broncos", "Blue Turf", "Virginia Tech Hokies",
    "Hokies", "West Virginia Mountaineers", "Mountaineers", "Louisville Cardinals",
    "Pitt Panthers", "Syracuse Orange", "Boston College Eagles",
    "North Carolina Tar Heels", "Tar Heels", "NC State Wolfpack", "Wolfpack",
    "Duke Blue Devils", "Blue Devils", "Georgia Tech Yellow Jackets",
    "Yellow Jackets", "Missouri Tigers", "Kansas Jayhawks", "Jayhawks",
    "Kansas State Wildcats", "Iowa State Cyclones", "Cyclones", "Minnesota Golden Gophers",
    "Golden Gophers", "Purdue Boilermakers", "Boilermakers", "Indiana Hoosiers",
    "Hoosiers", "Illinois Fighting Illini", "Fighting Illini", "Northwestern Wildcats",
    "Rutgers Scarlet Knights", "Scarlet Knights", "Maryland Terrapins", "Terrapins",
    "South Carolina Gamecocks", "Gamecocks", "Vanderbilt Commodores", "Commodores",
    "Texas Tech Red Raiders", "Red Raiders", "Arizona State Sun Devils", "Sun Devils",
    "Arizona Wildcats", "Utah State Aggies", "BYU Cougars", "Cougars",
    "Washington State Cougars", "Oregon State Beavers", "Beavers", "SMU Mustangs",
    "Mustangs", "Houston Cougars", "Cincinnati Bearcats", "Bearcats",
    "UCF Knights", "Memphis Tigers", "Tulane Green Wave", "Green Wave",
    "Appalachian State Mountaineers", "Liberty Flames", "James Madison Dukes",
    "Grambling Tigers", "Jackson State Tigers", "Howard Bison", "Florida A and M Rattlers",
    "Heisman Trophy", "Heisman", "Heisman Pose", "College Football Playoff",
    "National Championship", "Natty", "Rose Bowl Game", "Sugar Bowl", "Orange Bowl",
    "Cotton Bowl Classic", "Fiesta Bowl", "Peach Bowl", "Gator Bowl", "Citrus Bowl",
    "Alamo Bowl", "Holiday Bowl", "Liberty Bowl", "Music City Bowl", "Sun Bowl",
    "Bowl Game", "Bowl Season", "Bowl Eligible", "Conference Championship",
    "Big Ten", "Big Twelve", "SEC", "Southeastern Conference", "ACC",
    "Atlantic Coast Conference", "Pac Twelve", "Big East", "Mountain West",
    "American Athletic", "Sun Belt", "Mid American", "Conference USA",
    "Ivy League", "Independent", "Power Four", "Power Five", "Group of Five",
    "Division One", "FBS", "FCS", "Redshirt", "Redshirt Freshman", "Walk On",
    "Scholarship", "Transfer Portal", "Name Image Likeness", "Recruiting",
    "Five Star Recruit", "Blue Chip", "Commit", "Decommit", "Signing Day",
    "Spring Game", "Homecoming", "Student Section", "Marching Band", "Fight Song",
    "Rivalry Week", "The Game", "Iron Bowl", "Red River Rivalry", "Red River Shootout",
    "The Egg Bowl", "Egg Bowl", "Apple Cup", "Civil War", "Bedlam", "Holy War",
    "Backyard Brawl", "Paul Bunyan Trophy", "Old Oaken Bucket", "Floyd of Rosedale",
    "Little Brown Jug", "Axe", "Stanford Axe", "Victory Bell", "Game Day",
    "College GameDay", "Lee Corso", "Kirk Herbstreit", "Headgear Pick",
    "Touchdown Jesus", "Play Like a Champion Today", "Script Ohio", "Dotting the I",
    "Jump Around", "Enter Sandman", "Sandstorm", "Mr Brightside",
    "Sooner Schooner", "Ralphie", "Bevo", "Uga", "Smokey", "Mike the Tiger",
    "Reveille", "Traveler", "Sparty", "Brutus", "Bucky Badger", "Herky",
    "Tommy Trojan", "Oski", "Big Al", "Aubie", "Albert", "Cocky", "Chief Osceola",
    "Renegade", "Leprechaun", "War Eagle Flight"]);

  /* --- Events, media & culture --- */
  add("Event", ["Super Bowl", "Super Bowl Sunday", "Big Game", "Halftime Show",
    "Super Bowl Halftime Show", "Lombardi Trophy", "Vince Lombardi Trophy",
    "Super Bowl Ring", "Championship Ring", "Super Bowl MVP", "Media Day",
    "Opening Night", "Radio Row", "Super Bowl Commercial", "Puppy Bowl",
    "Pro Bowl Games", "NFL Draft", "Draft Day", "Draft Night", "Green Room",
    "Scouting Combine", "NFL Combine", "Free Agency Frenzy", "Legal Tampering",
    "Schedule Release", "Kickoff Game", "Kickoff Weekend", "Opening Day",
    "Week One", "Thanksgiving Game", "Thanksgiving Football", "Turkey Day",
    "Christmas Game", "Black Friday Game", "Monday Night Football",
    "Sunday Night Football", "Thursday Night Football", "Sunday Ticket",
    "RedZone", "Red Zone Channel", "Scott Hanson", "Octobox", "Whip Around",
    "NFL Network", "NFL Films", "Hard Knocks", "Quarterback", "Inside the NFL",
    "Football Night in America", "Pregame Show", "Postgame Show",
    "Countdown", "Gameday Morning", "Fox NFL Sunday", "The NFL Today",
    "Booth", "Broadcast Booth", "Skycam", "Telestrator", "First Down Line",
    "Yellow Line", "Al Michaels", "Cris Collinsworth", "Joe Buck", "Troy Aikman",
    "Jim Nantz", "Tony Romo", "Kevin Burkhardt", "Greg Olsen", "Mike Tirico",
    "Pat McAfee", "Terry Bradshaw", "Howie Long", "Michael Strahan",
    "Jimmy Johnson", "Rob Gronkowski", "Peyton and Eli", "ManningCast",
    "Do You Believe in Miracles", "Are You Ready for Some Football",
    "Hank Williams Junior", "Heavy Action", "Wild Card Weekend", "Wild Card Round",
    "Divisional Round", "Conference Championship Game", "AFC Championship",
    "NFC Championship", "AFC Championship Game", "NFC Championship Game",
    "Playoff Football", "January Football", "Playoff Push", "Win and In",
    "Division Title", "Division Champion", "Conference Champion", "World Champion",
    "Back to Back", "Three Peat", "Repeat", "Dynasty", "Undefeated Season",
    "Perfect Season", "Seventeen and Zero", "Nineteen and Zero", "Miami Dolphins Champagne",
    "Hall of Fame Game", "Hall of Fame Weekend", "Enshrinement", "Gold Jacket Ceremony",
    "Ring of Honor Ceremony", "Jersey Retirement", "Honors", "NFL Honors",
    "Walter Payton Man of the Year", "Comeback Player of the Year Award",
    "Offensive Player of the Year", "Defensive Player of the Year",
    "Offensive Rookie of the Year", "Defensive Rookie of the Year",
    "Coach of the Year Award", "Assistant Coach of the Year", "Salute to Service",
    "Crucial Catch", "My Cause My Cleats", "Play Sixty", "Punt Pass and Kick",
    "Flag Football", "Touch Football", "Two Hand Touch", "Backyard Football",
    "Pickup Game", "Pee Wee Football", "Pop Warner", "High School Football",
    "Friday Night Lights", "Texas High School Football", "Homecoming Game",
    "Rivalry Game", "Season Opener", "Season Finale", "Bye Week Blues",
    "Tailgate Party", "Watch Party", "Super Bowl Party", "Chili", "Wings",
    "Buffalo Wings", "Nachos", "Seven Layer Dip", "Guacamole", "Bratwurst",
    "Brats", "Cheese Curds", "Cheesehead", "Foam Finger", "Face Paint",
    "Body Paint", "Terrible Towel", "Rally Towel", "Cowbell", "Vuvuzela",
    "Bleachers", "Upper Deck", "Nosebleeds", "Fifty Yard Line Seats",
    "Club Seats", "Luxury Box", "Suite", "Season Tickets", "Season Ticket Holder",
    "Personal Seat License", "Stadium Beer", "Concession Stand", "Hot Dog",
    "Stadium Nachos", "Jumbotron Kiss Cam", "Kiss Cam", "The Wave",
    "Chant", "Fight Song", "Touchdown Song", "Victory Song", "Gameday",
    "Game Day", "Football Season", "Football Weather", "Sweater Weather",
    "Fall Sundays", "Autumn Sundays", "Sunday Funday", "Couch Potato",
    "Armchair Quarterback", "Monday Morning Quarterback", "Backseat Coach",
    "Superfan", "Fair Weather Fan", "Bandwagon", "Bandwagon Fan", "Diehard",
    "Die Hard Fan", "Lifelong Fan", "Homer", "Hater", "Fan Base", "Fandom",
    "Twelves", "Pats Nation", "Steeler Nation", "Cowboys Nation", "Chiefs Kingdom",
    "Bird Gang", "Fly Eagles Fly", "Skol", "Skol Vikings", "Who Dey", "Who Dat",
    "Go Pack Go", "Go Birds", "Go Hawks", "Bear Down", "Dilly Dilly",
    "Sco Bills", "Bills Mafia Table", "Sack Dance", "Salsa Dance", "Ickey Shuffle",
    "Dirty Bird", "Mile High Salute", "Squirrel Dance", "Kelce Dance",
    "Swag Surf", "Taylor Swift", "Swifties", "Traylor", "Tayvis",
    "Jalen Hurts Shove", "Kelce Bowl", "Manning Bowl", "Harbaugh Bowl",
    "Snow Game", "Blizzard Game", "Fog Game", "Mud Game", "Rain Game",
    "Cold Weather Game", "Frozen Field", "Lightning Delay", "Weather Delay"]);
  /* --- Everyday vocabulary & deeper scheme jargon --- */
  add("Play & Term", ["Win", "Loss", "Tie", "Score", "Points", "Yards", "Yard",
    "Inches", "Down", "Drive", "Series", "Possession", "Offense", "Defense",
    "Kick", "Pass", "Run", "Rush", "Throw", "Carry", "Attempt", "Target",
    "Block", "Blocking", "Tackling", "Hit", "Stop", "Stuff", "Fake", "Pump",
    "Pass Protection", "Pass Pro", "Pass Block", "Run Block", "Coverage",
    "Rushing", "Passing", "Receiving", "Return", "Kick Return", "Punt Return",
    "Field Goal Attempt", "Field Goal Range", "Try", "Two Point Try", "Muff",
    "Free Kick", "Fair Catch Kick", "Drop Kick", "Onside", "Squib", "Quarter",
    "Half", "Period", "Season", "Game", "Week", "Schedule", "Standings",
    "Record", "Streak", "Season Sweep", "Division Rival", "Rival", "Opponent",
    "Home", "Away", "Visitor", "Crowd", "Fans", "Stadium", "Field", "Ball",
    "Ref", "Hut", "Hut Hut Hike", "Down Set Hut", "Ready Break", "Break",
    "Set", "Kill Kill", "Alert", "Check With Me", "Mike", "Sam", "Will", "Jack",
    "Rover", "Monster", "Nickel", "Whip", "Split End", "Flanker", "X Receiver",
    "Y Receiver", "Z Receiver", "H Back", "Wingback", "Fullback Dive",
    "Statue of Liberty", "Hook and Ladder", "Hook and Lateral", "Halfback Pass",
    "Double Reverse", "End Around", "Fumblerooski", "Tackle Eligible",
    "Mesh", "Mesh Point", "Smash", "Levels", "Flood", "Four Verticals", "Verts",
    "Mills", "Yankee", "Dagger", "Sail", "Snag", "Stick", "Shallow Cross",
    "Texas", "Angle", "Choice Route", "Option Route", "Whip Route", "Sluggo",
    "Post Corner", "Double Move", "Stop and Go", "Hitch", "Hitch and Go",
    "Speed Out", "Skinny Post", "Nine Route", "Streak", "Screen",
    "Tunnel Screen", "Slip Screen", "Middle Screen", "Toss Sweep", "Buck Sweep",
    "Duo", "Wham", "Split Zone", "Bash", "Crack Toss", "Pin and Pull",
    "Gap Scheme", "Zone Scheme", "Wide Zone", "Cutback", "Bounce", "Downhill",
    "Between the Tackles", "Off Tackle", "A Gap", "B Gap", "C Gap",
    "Three Technique", "One Technique", "Zero Technique", "Five Technique",
    "Wide Nine", "Overload", "Simulated Pressure", "Zone Blitz", "Fire Zone",
    "Corner Blitz", "Safety Blitz", "Delayed Blitz", "Green Dog",
    "Double A Gap", "Mug", "Robber", "Bracket", "Cloud", "Sky", "Quarters",
    "Palms", "Match Coverage", "Pattern Match", "Banjo", "Trail", "Bail",
    "Off Coverage", "Jam", "Chuck", "Reroute", "Inside Leverage",
    "Outside Leverage", "Hip Pocket", "In Phase", "Undercut", "High Point",
    "Box Out", "Fifty Fifty Ball", "Jump Ball", "Contested Catch",
    "Back Shoulder", "Back Shoulder Fade", "Throw Him Open", "Anticipation",
    "Window", "Throwing Lane", "Sight Adjustment", "Hot Route", "Hot Read",
    "Progression", "Read", "Pre Snap Read", "Post Snap", "Disguise", "Rotate",
    "Late Rotation", "Single High", "Two High", "Two Deep", "Box", "Light Box",
    "Loaded Box", "Stacked Box", "Eight in the Box", "Alley", "Force Player",
    "Set the Edge", "Fill", "Scrape", "Two Gap", "One Gap", "Anchor", "Shed",
    "Stack and Shed", "Get Off", "First Step", "Hand Fighting", "Long Arm",
    "Club", "Club Rip", "Ghost", "Dip and Rip", "Cross Chop", "Hump Move",
    "Counter Move", "Sack Fumble", "Peanut Punch", "Punch Out", "Ball Security",
    "High and Tight", "Fumble Drill", "Oklahoma Drill", "Bull in the Ring",
    "Two a Days", "Padded Practice", "Walk Through", "Install", "Scheme",
    "Concept", "Package", "Personnel", "Eleven Personnel", "Twelve Personnel",
    "Twenty One Personnel", "Heavy Package", "Jumbo Package", "Sixth Lineman",
    "Unbalanced Line", "Condensed Split", "Wide Split", "Stack", "Twins",
    "Doubles", "Quads", "Flexbone", "Diamond", "Full House", "Power I",
    "Pro Set", "Split Backs", "Offset I", "Strong I", "Weak I", "Under Center",
    "Sugar Huddle", "Freeze Play", "Draw Them Offside", "Silent Count",
    "Clap Cadence", "Crowd Noise", "Home Cooking", "Clutch",
    "Fourth Quarter Comeback", "Game Winning Drive", "Walk Off",
    "Last Second Field Goal", "Heartbreaker", "Choke", "Collapse", "Blown Lead",
    "Rally", "Halftime Adjustments", "Opening Script", "First Fifteen",
    "Analytics", "Expected Points", "Success Rate", "Win Probability",
    "Fourth Down Decision", "Take the Points", "Trust the Kicker", "Iced",
    "Icing the Kicker", "Double Doink", "Pass Rush Win Rate", "Pressure Rate",
    "Snap Count Share", "Touches", "Targets", "Air Yards", "Yards Per Route Run",
    "Target Share", "Red Zone Target", "Goal Line Back", "Third Down Back",
    "Change of Pace Back", "Committee Backfield", "Workhorse", "Bellcow Back",
    "Possession Receiver", "Deep Threat", "Burner", "Speedster", "Route Runner",
    "Move Tight End", "Blocking Tight End", "Swing Tackle", "Utility Lineman",
    "Rotational Rusher", "Run Stuffer", "Space Eater", "Interior Rusher",
    "Off Ball Linebacker", "Coverage Linebacker", "Box Safety", "Center Fielder",
    "Slot Corner", "Press Corner", "Return Specialist", "Core Special Teamer",
    "Kickoff Specialist", "National Anthem", "Star Spangled Banner", "Flyover",
    "Fireworks", "Pregame", "Player Introductions", "Tunnel Entrance", "Pyro",
    "Hype Video", "Ring Ceremony", "Banner Unveiling", "Championship Banner",
    "Parade", "Championship Parade", "Duck Boats", "Boat Parade"]);

  /* --- Famous plays, games, moments & franchise history --- */
  add("Moment", ["The Immaculate Reception", "Immaculate Extension",
    "Immaculate Deflection", "The Catch Two", "Dwight Clark", "The Play",
    "The Band Is on the Field", "Bluegrass Miracle", "Kick Six",
    "Miracle at Michigan", "Miracle in Miami", "Bush Push", "Scott Norwood",
    "Wide Right Norwood", "Miracle at the Meadowlands",
    "Miracle at the New Meadowlands", "Malcolm Butler Interception",
    "Butler Interception", "Malcolm Go", "Beast Quake", "Dez Caught It",
    "The Comeback", "Frank Reich", "Ghost to the Post", "Sea of Hands",
    "Holy Roller", "Heidi Game", "Heidi Bowl", "Snowplow Game", "The Tackle",
    "One Yard Short", "Mike Jones Tackle", "Bountygate", "Bottlegate",
    "Sneakers Game", "Greatest Game Ever Played", "Freezer Bowl",
    "Thirteen Seconds", "Twenty Eight to Three", "Fourth and Twenty Six",
    "Leon Lett", "Garo Yepremian", "Jim Marshall Wrong Way", "Wrong Way Run",
    "Roy Riegels", "Flutie Hail Mary", "Doug Flutie", "Flutie Flakes",
    "Hail Flutie", "Desmond Howard", "Heisman Pose Howard", "Tommie Frazier",
    "Vince Young Rose Bowl", "Boise State Statue of Liberty", "Ian Johnson",
    "Appalachian State Upset", "App State Michigan", "Prayer at Jordan Hare",
    "Chris Davis Return", "Kick Bama Kick", "Second and Twenty Six",
    "Tua Tagovailoa", "Tua to Smitty", "Honey Badger", "Tyrann Mathieu",
    "Johnny Football", "Tebow Time", "Tebowing", "Brady Manning Rivalry",
    "Brady Belichick", "The Patriot Way", "Do Your Job",
    "We Are On to Cincinnati", "On to Cincinnati", "Brady Suspension",
    "Mahomes Magic", "Elway Helicopter", "The Helicopter", "Earnest Byner",
    "Red Right Eighty Eight", "Wardrobe Malfunction", "Left Shark",
    "Blackout Bowl", "Super Bowl Blackout", "Vinatieri Snow Kick",
    "Kevin Dyson", "Frank Wycheck", "Diggs Catch", "Nick Foles Catch",
    "David Tyree", "Mario Manningham", "Plaxico Burress", "Should Have Run",
    "Pete Carroll Pass Play", "Odell One Handed", "Odell Catch",
    "Randy Moss Mooning", "Moss Mooning", "Owens Star Dance",
    "Sharpie Celebration", "Popcorn Celebration", "Ochocinco River Dance",
    "Joe Horn Cell Phone", "Cell Phone Celebration", "Ickey Woods",
    "Deion High Step", "High Step", "LeRoy Butler", "Handshake Gate",
    "Harbaugh Schwartz", "Falcons Blown Lead", "Atlanta Collapse",
    "Wide Right Buffalo", "Four Straight Super Bowls", "Purple Reign",
    "Steelers Six Rings", "Steel Curtain Dynasty", "Niners Dynasty",
    "Cowboys Dynasty", "Patriots Dynasty", "Chiefs Dynasty", "Packers Dynasty",
    "Lombardi Packers", "Undefeated Dolphins", "Perfect Dolphins",
    "Seventy Two Dolphins", "Eighty Five Bears", "Super Bowl Shuffle",
    "Greatest Show on Turf", "The Greatest Show on Turf", "Killer Bees",
    "Orange Crush", "Doomsday Defense", "No Name Defense", "Fearsome Foursome",
    "New York Sack Exchange", "Sack Exchange", "Big Blue Wrecking Crew",
    "Gritz Blitz", "Dome Patrol", "Silver and Black", "Commitment to Excellence",
    "Just Win Baby", "Al Davis", "Pride and Poise", "Ground Chuck", "Martyball",
    "The Hogs", "The Fun Bunch", "Smurfs", "The Posse", "Three Amigos",
    "Triplets", "Bruise Brothers", "Mile High Miracle", "The Comeback Kid",
    "Captain Comeback", "Captain Checkdown", "The Sheriff", "The Golden Boy",
    "Golden Arm", "Slash", "Air McNair", "Ironhead", "Neon Deion",
    "The Minister of Defense", "Minister of Defense", "The Freak",
    "The Snake", "The Mad Bomber", "The Guarantee", "Namath Guarantee",
    "Joe Willie", "Johnny U", "Slingin Sammy", "Night Train", "Night Train Lane",
    "Bullet Bob Hayes", "Bullet Bob", "Crazylegs", "Crazylegs Hirsch",
    "The Galloping Ghost", "Galloping Ghost", "The Four Horsemen",
    "Four Horsemen", "Win One for the Gipper", "The Gipper", "Gipper",
    "Rudy Chant", "Rudy Rudy Rudy", "Joe Cool", "Montana to Clark",
    "Montana to Rice", "Montana to Taylor", "John Taylor Catch",
    "Elway to Jackson", "Steve Young Run", "Young Scramble", "Rice Records",
    "Emmitt Smith Record", "Payton Record", "Marino Records", "Fake Spike",
    "Marino Fake Spike", "This One Is for John", "Pat Bowlen", "Mister B",
    "Jerry Jones Buys Cowboys", "Landry Fired", "Herschel Walker Trade",
    "The Great Trade Robbery", "Great Trade Robbery", "Ricky Williams Trade",
    "Ditka Trades Draft", "Eli Manning Trade", "Manning Rivers Trade",
    "Elway Trade", "Mayflower Trucks", "Mayflower Vans", "Colts Move",
    "Browns Move", "Art Modell", "Modell Move", "Cleveland Browns Return",
    "Rams Move", "Raiders Move", "Chargers Move", "Oilers Move",
    "Houston Oilers", "Luv Ya Blue", "Los Angeles Raiders", "Oakland Raiders",
    "St Louis Rams", "San Diego Chargers", "Baltimore Colts",
    "Washington Football Team", "Tennessee Oilers", "Phoenix Cardinals",
    "St Louis Cardinals", "Chicago Cardinals", "Boston Patriots",
    "New York Titans", "Dallas Texans", "Cleveland Rams", "Portsmouth Spartans",
    "Decatur Staleys", "Chicago Staleys", "Duluth Eskimos", "Canton Bulldogs",
    "Frankford Yellow Jackets", "Pottsville Maroons", "Providence Steam Roller",
    "Steagles", "Card Pitt", "AFL NFL Merger", "The Merger", "AFL",
    "American Football League", "USFL", "XFL", "UFL", "Arena Football",
    "Arena League", "AAF", "World League", "NFL Europe", "CFL",
    "Canadian Football", "Grey Cup", "Rouge", "Three Downs", "Twelve Players",
    "Lockout", "Strike", "Replacement Players", "Scabs", "Eighty Seven Strike",
    "Strike Season", "CBA", "Collective Bargaining Agreement", "NFLPA",
    "Players Association", "Union", "Roger Goodell", "Goodell Boos",
    "Commissioner Goodell", "Commissioner", "The Shield", "Protect the Shield",
    "NFL Shield", "Pete Rozelle", "Rozelle", "Paul Tagliabue", "Bert Bell",
    "Robert Kraft", "Kraft Family", "Kraft Ring", "Putin Ring", "Jerry Jones",
    "Jerry Jones Bus", "Jerry Jones Suite", "Cowboys Star", "The Star",
    "Cowboys Stadium", "Mo Lewis Hit", "Mo Lewis", "Drew Bledsoe", "Bledsoe",
    "Jimmy Garoppolo", "Jimmy G", "Garoppolo Trade", "Mac Jones", "Drake Maye",
    "Brady Sixth Round", "Pick One Ninety Nine", "One Ninety Nine",
    "Brady Combine Photo", "Brady Bucs", "Brady Tampa", "Lombardi Toss",
    "Trophy Toss", "Tampa Boat Parade", "Brady Retirement", "Brady Unretirement",
    "Brady Six Rings", "Brady Seven Rings", "Manning Neck Surgery",
    "Omaha Omaha", "Tush Push Ban", "Tush Push Debate", "Lamar Jackson Hurdle",
    "Kelce Screen", "Jason Kelce Parade Speech", "Kelce Parade Speech",
    "Hungry Dogs Run Faster", "No One Likes Us We Do Not Care",
    "Kelce Shirtless", "Kelce Shirtless Buffalo", "Broad Street Parade",
    "SMU Death Penalty", "Death Penalty", "Pony Excess", "Pony Express"]);

  /* --- Pop culture: film, TV, games, music, media & commercials --- */
  add("Pop Culture", ["Rudy", "Remember the Titans", "Friday Night Lights",
    "The Blind Side", "Any Given Sunday", "Jerry Maguire", "Show Me the Money",
    "You Had Me at Hello", "The Longest Yard", "Mean Machine", "Varsity Blues",
    "I Do Not Want Your Life", "The Waterboy", "Bobby Boucher", "Water Sucks",
    "Gatorade Is Better", "Draft Day", "Concussion", "Invincible",
    "We Are Marshall", "The Replacements", "Shane Falco", "Little Giants",
    "Necessary Roughness", "Brians Song", "Brian Piccolo", "North Dallas Forty",
    "Air Bud Golden Receiver", "Facing the Giants", "Silver Linings Playbook",
    "Leatherheads", "Semi Tough", "Wildcats", "The Program", "Big Fan",
    "Eighty for Brady", "Radio", "Gridiron Gang", "Undefeated", "Ace Ventura",
    "Ray Finkle", "Laces Out Finkle", "The Express", "Everybodys All American",
    "Johnny Be Good", "Lucas", "All the Right Moves", "The Best of Times",
    "Paper Lion", "Heaven Can Wait", "Black Sunday", "The Game Plan",
    "Safety Movie", "Woodlawn", "When the Game Stands Tall", "Greater",
    "The Junction Boys", "Home Team", "Kevin James Home Team", "Rise",
    "Ballers", "Coach", "Coach Hayden Fox", "Blue Mountain State",
    "Thad Castle", "All American", "Last Chance U", "Quarterback Netflix",
    "Receiver Netflix", "The League", "Ted Lasso", "Ted Lasso Football",
    "Believe", "Roy Kent", "Friday Night Lights TV", "Coach Taylor",
    "Eric Taylor", "Tami Taylor", "Tim Riggins", "Texas Forever",
    "Clear Eyes Full Hearts", "Clear Eyes Full Hearts Cannot Lose",
    "Dillon Panthers", "East Dillon Lions", "Matt Saracen", "Smash Williams",
    "Jason Street", "Landry Clarke", "Vince Howard", "Buddy Garrity",
    "Rod Tidwell", "Cuba Gooding Junior", "Paul Crewe", "Adam Sandler",
    "Burt Reynolds", "Coach Boone", "Coach Yoast", "Denzel Washington",
    "Herman Boone", "Left Side Strong Side", "Michael Oher", "Leigh Anne Tuohy",
    "Sandra Bullock", "Vince Papale", "Mark Wahlberg", "Rudy Ruettiger",
    "Sean Astin", "Uncle Rico", "Napoleon Dynamite", "Back in Eighty Two",
    "Over Them Mountains", "Al Bundy", "Polk High", "Four Touchdowns in One Game",
    "Four Touchdowns", "Married with Children", "Forrest Gump",
    "Run Forrest Run", "Springfield Atoms", "Stan Taylor", "Peter Griffin Football",
    "Family Guy Football", "Cleveland Brown", "The Cleveland Show",
    "Charlie Brown Football", "Lucy Pulls the Football", "Lucy and the Football",
    "Snoopy Football", "Peanuts Football", "Good Grief", "Aaugh",
    "Miss Piggy Football", "Bo Knows", "Bo Knows Football", "Bo Jackson Nike",
    "Nike Football", "Madden", "Madden NFL", "Madden Curse", "Madden Cover",
    "Madden Cover Curse", "Boom", "Boom Tough Actin Tinactin", "Turducken",
    "Madden Cruiser", "Tecmo Bowl", "Tecmo Super Bowl", "Tecmo Bo", "NFL Blitz",
    "NFL Street", "NFL Two K", "ESPN NFL Two K Five", "Mutant Football League",
    "Mutant League", "Backyard Football", "NCAA Football",
    "College Football Twenty Five", "EA Sports", "It Is in the Game",
    "Retro Bowl", "Blood Bowl", "Front Page Sports", "Quarterback Club",
    "Joe Montana Football", "John Elway Quarterback", "Ten Yard Fight",
    "Cyberball", "Bill Walsh College Football", "Ultimate Team",
    "Franchise Mode", "Superstar Mode", "Ninety Nine Club", "Ninety Nine Overall",
    "Overall Rating", "Truck Stick", "Hit Stick", "Right Stick",
    "Monday Night Football Theme", "Heavy Action",
    "Are You Ready for Some Football", "All My Rowdy Friends", "Hank Junior",
    "Bocephus", "Faith Hill", "Carrie Underwood",
    "Waiting All Day for Sunday Night", "Sunday Night Football Theme", "Pink",
    "Chris Stapleton", "Fox NFL Theme", "Fox Robot", "Cleatus",
    "Cleatus the Robot", "CBS NFL Theme", "NBC Chimes", "NFL on CBS",
    "NFL on Fox", "NFL on NBC", "NFL on ESPN", "ESPN", "Fox Sports",
    "CBS Sports", "NBC Sports", "Prime Video", "Amazon Prime",
    "Netflix Christmas Games", "Peacock", "YouTube TV", "Sunday Ticket YouTube",
    "DirecTV", "Sirius XM NFL Radio", "NFL Radio", "Westwood One", "Radio Call",
    "Radio Broadcast", "Local Radio", "Homer Call", "Play by Play",
    "Play by Play Announcer", "Color Analyst", "Rules Analyst", "Mike Pereira",
    "Gene Steratore", "Dean Blandino", "Terry McAulay", "Walt Anderson",
    "Ed Hochuli", "Guns Hochuli", "Hochuli", "Tony Corrente", "Carl Cheffers",
    "Jerome Boger", "Clete Blakeman", "Brad Allen", "Shawn Hochuli",
    "Bill Vinovich", "Ron Torbert", "Craig Wrolstad", "Referee Announcement",
    "After Further Review", "The Ruling on the Field", "The Ruling on the Field Stands",
    "Upon Further Review", "Pat Summerall", "Keith Jackson", "Whoa Nellie",
    "Dick Enberg", "Oh My", "Brent Musburger", "You Are Looking Live",
    "Chris Berman", "Boomer Berman", "He Could Go All the Way",
    "Back Back Back", "Rumblin Bumblin Stumblin", "Tom Jackson", "Stuart Scott",
    "Booyah", "Cool as the Other Side of the Pillow", "Howard Cosell",
    "Frank Gifford", "Dandy Don", "Don Meredith", "Turn Out the Lights",
    "Turn Out the Lights the Party Is Over", "Dan Dierdorf", "Dennis Miller",
    "Tony Kornheiser", "Spider Two Y Banana", "Gruden QB Camp", "Ron Jaworski",
    "Jaws", "Mike Mayock", "Mel Kiper", "Kiper Junior", "Todd McShay",
    "Daniel Jeremiah", "Louis Riddick", "Booger McFarland", "Booger Mobile",
    "Romostradamus", "Hello Friends", "Kevin Harlan", "Rich Eisen",
    "Run Rich Run", "Good Morning Football", "Kyle Brandt", "Peter Schrager",
    "Kay Adams", "Erin Andrews", "Michele Tafoya", "Pam Oliver", "Lisa Salters",
    "Melissa Stark", "Charissa Thompson", "Hannah Storm", "Andrea Kremer",
    "Suzy Kolber", "I Want to Kiss You", "Lesley Visser", "Phyllis George",
    "Jayne Kennedy", "Adam Schefter", "Schefty", "Ian Rapoport", "RapSheet",
    "Tom Pelissero", "Jay Glazer", "Josina Anderson", "Dianna Russini",
    "Albert Breer", "Peter King", "Football Morning in America", "Bill Simmons",
    "The Ringer", "Grantland", "Sports Guy", "Colin Cowherd", "The Herd",
    "Skip Bayless", "Undisputed", "Stephen A Smith", "First Take",
    "Shannon Sharpe Undisputed", "Unc", "Nightcap", "Pardon the Interruption",
    "PTI", "Around the Horn", "Get Up", "NFL Live", "Sunday NFL Countdown",
    "Monday Night Countdown", "The Pat McAfee Show", "Pat McAfee Show",
    "New Heights", "New Heights Podcast", "Bussin With the Boys", "Will Compton",
    "Taylor Lewan", "Pardon My Take", "PMT", "Big Cat", "Barstool",
    "Barstool Sports", "Fantasy Footballers", "Matthew Berry", "Fantasy Life",
    "Fantasy Focus", "Field Yates", "Mina Kimes", "Dan Orlovsky",
    "Orlovsky Safety", "Marcus Spears", "Swagu", "Ryan Clark", "Damien Woody",
    "Domonique Foxworth", "Bart Scott", "Cannot Wait", "Nate Burleson",
    "Kyle Long", "Steve Mariucci", "Mooch", "Playmaker", "The Playmaker",
    "Fourth and One Podcast", "Funky Friday", "Sharpe and Ocho", "Club Shay Shay",
    "Steve Smith Senior", "Brian Baldinger", "Baldys Breakdowns", "Baldy",
    "PFF", "Pro Football Focus", "PFF Grade", "Football Outsiders",
    "Next Gen Stats", "Pro Football Reference", "Stathead", "DraftKings",
    "FanDuel", "BetMGM", "Caesars Sportsbook", "Bet Slip", "Same Game Parlay",
    "Prop Bet", "Player Prop", "Anytime Touchdown", "Anytime Touchdown Scorer",
    "Moneyline", "Vegas Line", "Line Movement", "Sharp Money", "Public Money",
    "Lock", "Lock of the Week", "Survivor Pool", "Pick Em", "Pickem", "Squares",
    "Super Bowl Squares", "Office Pool", "Sleeper App", "ESPN Fantasy",
    "Yahoo Fantasy", "NFL Fantasy", "Sleeper", "Dynasty League", "Keeper League",
    "Redraft", "Best Ball", "Auction Draft", "Snake Draft", "Draft Kit",
    "Cheat Sheet", "Rankings", "Tiers", "Waiver Claim", "FAAB",
    "Starting Lineup", "Flex Spot", "Superflex", "Two Quarterback League", "PPR",
    "Half PPR", "Standard Scoring", "IDP", "Kicker Roulette", "Streaming Defense",
    "Bye Week Fill In", "Handcuff", "League Winner", "Bust", "Breakout",
    "Late Round Flier", "Zero RB", "Hero RB", "Robust RB", "Late Round QB",
    "Draft Capital", "ADP", "Average Draft Position", "Trade Value Chart",
    "Trade Calculator", "Last Place Punishment", "Waffle House Punishment",
    "Commish", "League Chat", "Group Chat", "Sacko", "The Shiva", "Shiva Bowl",
    "Toilet Bowl", "Consolation Bracket", "Championship Week", "Fantasy Playoffs",
    "Fantasy Championship", "Fantasy Title", "Mean Joe Greene Coke",
    "Hey Kid Catch", "Coke Commercial", "Budweiser Clydesdales", "Clydesdales",
    "Bud Bowl", "Bud Light", "Dilly Dilly Commercial", "Doritos Crash the Super Bowl",
    "Doritos Commercial", "Apple Nineteen Eighty Four", "Nineteen Eighty Four Ad",
    "Wassup", "Wassup Commercial", "Terry Tate", "Terry Tate Office Linebacker",
    "Office Linebacker", "Jake from State Farm", "State Farm", "Nationwide",
    "Nationwide Is on Your Side", "Chicken Parm You Taste So Good", "Chicken Parm",
    "Peyton Manning Commercial", "Papa Johns", "Papa John", "Priceless",
    "E Trade Baby", "Etrade Baby", "GoDaddy", "Snickers Betty White",
    "Betty White", "Cindy Crawford Pepsi", "Pepsi Commercial", "Pepsi Halftime",
    "Apple Music Halftime", "Bridgestone Halftime", "Puppy Bowl Animal Planet",
    "Kitten Bowl", "Fish Bowl", "Halftime Performer", "Halftime Headliner",
    "Prince Purple Rain", "Purple Rain", "Prince Halftime", "Beyonce Halftime",
    "Beyonce", "Michael Jackson Halftime", "U Two", "U Two Halftime",
    "Bruno Mars", "Bruno Mars Halftime", "Lady Gaga", "Lady Gaga Halftime",
    "Rihanna", "Rihanna Halftime", "Usher", "Usher Halftime", "Kendrick Lamar",
    "Kendrick Halftime", "Not Like Us", "Shakira", "Jennifer Lopez", "J Lo",
    "Katy Perry", "Katy Perry Halftime", "Left Shark Katy Perry",
    "Justin Timberlake", "Janet Jackson", "Nipplegate", "The Weeknd",
    "Weeknd Halftime", "Coldplay", "Tom Petty", "Bruce Springsteen", "The Boss",
    "The Who", "Paul McCartney", "Rolling Stones", "Madonna", "Black Eyed Peas",
    "Dr Dre", "Snoop Dogg", "Eminem", "Mary J Blige", "Fifty Cent", "Bad Bunny",
    "Bad Bunny Halftime", "Up with People", "Marching Band Halftime",
    "Grambling Band", "Drumline", "Diana Ross Helicopter", "Aerosmith NSYNC",
    "Britney Spears Halftime", "Nelly Halftime", "Whitney Houston Anthem",
    "Whitney Houston National Anthem", "Anthem Singer", "Anthem Length",
    "Taylor Swift Suite", "Swift Suite", "Kelce Swift", "Travis and Taylor",
    "Kelce Jam", "Gronk Party Bus", "Gronk Spike", "Gronk Cruise",
    "Yo Soy Fiesta", "Antonio Brown Exit", "AB Exit", "Big Chest",
    "Ochocinco Name Change", "Pacman Jones", "Adam Pacman Jones",
    "Money Sign", "Manziel Money Sign", "Cam Newton Dab", "The Dab", "Dabbing",
    "Cam Superman", "Superman Celebration", "OBJ Hair", "Odell Kicking Net",
    "Kicking Net Proposal", "Kicking Net Fight", "Marshawn Skittles", "Skittles",
    "Beast Mode Skittles", "I Am Just Here So I Will Not Get Fined",
    "So I Will Not Get Fined", "Boss Do Not Mean Nothing", "Bout That Action Boss",
    "Marshawn Media Day", "Lynch Media Day", "Richard Sherman Rant",
    "Sherman Rant", "Sherman Crabtree", "Do Not You Ever Talk About Me",
    "Sorry Receiver", "Mediocre Receiver", "Sherman Choke Sign",
    "Bill Belichick Hoodie", "Belichick Hoodie", "Cutoff Hoodie",
    "Belichick Press Conference", "Belichick Grumpy", "Belichick Smile",
    "Belichick North Carolina", "Belichick UNC", "Dennis Green Rant",
    "They Are Who We Thought They Were", "Who We Thought They Were",
    "Crown Their Ass", "Jim Mora Playoffs", "Playoffs Rant",
    "Playoffs You Kidding Me", "Playoffs Question Mark", "Herm Edwards Rant",
    "You Play to Win the Game", "Play to Win the Game", "Mike Gundy Rant",
    "I Am a Man I Am Forty", "I Am a Man", "Come After Me", "Mike Singletary Rant",
    "Cannot Win with Them", "Vernon Davis Benched", "Rex Ryan Snacks",
    "Rex Ryan Foot", "Snack", "Goddamn Snack", "Buddy Ryan Punch",
    "Kevin Gilbride", "Sideline Punch", "Jim Harbaugh Khakis", "Harbaugh Khakis",
    "Khakis", "Enthusiasm Unknown to Mankind", "Attack Each Day",
    "Who Has It Better Than Us", "Nobody", "Jim Harbaugh Steak",
    "Andy Reid Cheeseburger", "Reid Cheeseburger", "Andy Reid Mustache",
    "Andy Reid Hawaiian Shirt", "Big Red", "Andy Reid Big Red",
    "Andy Reid Time Management", "Reid Clock Management", "Andy Reid Hot Dog",
    "Coach Prime Sunglasses", "Coach Prime Louis Vuitton", "Colorado Coach Prime",
    "Dan Campbell Kneecaps", "Bite a Kneecap", "Kneecaps",
    "Dan Campbell Press Conference", "Dan Campbell Coffee", "Two Venti Coffees",
    "Dan Campbell Lions", "Grit Lions", "Sean McVay Memory", "McVay Memory",
    "Sean McVay Young", "McVay Effect", "Kyle Shanahan Hat", "Shanahan Flat Brim",
    "Shanahan Play Sheet", "Mike Tomlin Quotes", "The Standard Is the Standard",
    "Standard Is the Standard", "Tomlin Quotes", "Tomlin Winning Seasons",
    "Tomlin Never Losing Season", "Mike McCarthy Playoffs", "McCarthy Playoffs",
    "Nick Sirianni Fly Eagles Fly", "Sirianni Sideline", "Sirianni Taunting",
    "Sirianni Yelling", "Sirianni Fans", "Jerry Jones Press Conference",
    "Jerry Jones Radio", "Jerry World Video Board", "Sports Illustrated",
    "SI Cover", "SI Cover Jinx", "Cover Jinx", "Sports Illustrated Cover Jinx",
    "NFL Films Music", "Sam Spence", "John Facenda", "Voice of God",
    "Frozen Tundra Facenda", "Autumn Wind", "The Autumn Wind",
    "The Autumn Wind Is a Raider", "Steve Sabol", "Ed Sabol", "NFL Films Presents",
    "Americas Game", "A Football Life", "Football Life", "The Timeline",
    "Thirty for Thirty", "Thirty for Thirty Football", "Two Bills",
    "The U Documentary", "Bo Jackson Thirty for Thirty", "You Do Not Know Bo",
    "Four Falls of Buffalo", "Elway to Marino", "The Band That Would Not Die",
    "Brian and the Boz", "The Boz", "Brian Bosworth", "Al Davis vs the NFL",
    "Al Davis vs NFL", "Untold", "Untold Netflix", "Johnny Football Untold",
    "Swamp Kings", "Last Chance U Netflix", "Cheer", "Cheer Netflix", "Navarro",
    "Netflix Quarterback", "Kirk Cousins Quarterback", "You Like That",
    "Kirk Cousins You Like That", "Hard Knocks Cowboys", "Hard Knocks Jets",
    "Hard Knocks Bengals", "Hard Knocks Lions", "Hard Knocks In Season",
    "Hard Knocks Offseason", "Liev Schreiber", "Hard Knocks Narrator",
    "Peytons Places", "Elis Places", "Omaha Productions", "ManningCast Guests",
    "ManningCast Monday", "Peyton Manning SNL", "United Way SNL",
    "Peyton Manning United Way", "Peyton Manning Saturday Night Live",
    "Tom Brady SNL", "Brady SNL", "Brady Roast", "Tom Brady Roast",
    "The Roast of Tom Brady", "Netflix Roast", "Brady Netflix", "Brady Fox",
    "Tom Brady Fox Booth", "Brady Broadcasting", "Brady Raiders Owner",
    "Brady Ownership", "Brady Birmingham", "Brady Aston Villa", "Brady Gisele",
    "Gisele", "Brady Divorce", "Brady Avocado Ice Cream", "Avocado Ice Cream",
    "TB Twelve", "TB Twelve Method", "Pliability", "Pliable", "Brady Diet",
    "Brady Nightshades", "Brady Tomatoes", "Brady Water", "Brady Bunch",
    "Tom Brady Combine", "Brady Shirtless Combine", "Brady Draft",
    "Handsome Jimmy", "Mac Jones Benched", "Patriots Post Brady", "Brady Boat",
    "Brady Boat Parade", "Brady Lombardi Toss", "Bucs Boat Parade",
    "Tom Brady Boat", "Brady Drunk", "Brady Tequila", "Gronk Lombardi Toss"]);

})();
